"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var validate_middleware_1 = require("../middlewares/validate.middleware");
var auth_schema_1 = require("../schemas/auth.schema");
var auth_controller_1 = require("../controllers/auth.controller");
var router = (0, express_1.Router)();
router.post("/register", (0, validate_middleware_1.validate)(auth_schema_1.registerSchema), auth_controller_1.register);
router.post("/login", (0, validate_middleware_1.validate)(auth_schema_1.loginSchema), auth_controller_1.login);
exports.default = router;
